### PR TITLE
Update BrainMessage.m

### LINKED ISSUE #1: spaces not permitted in message
(Just opening this issue as documentation.)

Note: Spaces are not allowed in the message. If you include spaces, you'll get:

```
Error using containers.Map/subsref
The specified key is not present in this container.
```

### PR DESCRIPTION
**Pull request by dmd**
Only A-Z0-9 are in `BrainLetters.mat`, so remove nonmatching characters.  Closes #1.

### CODE REVIEW

**Comment by vsoch** [comment]
I can't test this, but if it works for you (and you can verify / show me some examples) I'd be happy to merge.

**Comment by dmd** [comment]
```
>> message='Hello World_@foo123;"\nbeer{'

message =

    'Hello World_@foo123;"\nbeer{'

>> message = upper(message)

message =

    'HELLO WORLD_@FOO123;"\NBEER{'

>> message(regexp(message,'[^A-Z0-9]'))=[]

message =

    'HELLOWORLDFOO123NBEER'

>>
```

**Comment by vsoch** [comment]
This looks good! Are you able to resolve conflicts or should I take a shot?

**Comment by dmd** [comment]
Resolved. It was just a whitespace conflict  at EOF - I removed a newline in both my PRs.

**Comment by vsoch** [comment]
That's very funny :0) Thanks @dmd, happy holidays!

**Pull request merged**
